import type { Metadata } from "next";
import "./globals.scss";
import NextTopLoader from "nextjs-toploader";

import { Providers } from "@/app/providers";

export const metadata: Metadata = {
  title: "GALAMAT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hy" suppressHydrationWarning={true}>
      <body>
        <NextTopLoader />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
